[package]
name = "fel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
git2 = "0.17.2"
serde = {version = "1.0.186", features = ["derive"]}
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
